const simpleGit = require("simple-git");
const axios = require("axios");
const fs = require("fs");
const path = require("path");

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_API = "https://api.github.com";

const headers = {
  Authorization: `Bearer ${GITHUB_TOKEN}`,
  Accept: "application/vnd.github+json",
  "X-GitHub-Api-Version": "2022-11-28",
};

/**
 * Create a new GitHub repository (public).
 * If the repo already exists, fetch and return it instead.
 */
const createRepo = async (repoName) => {
  try {
    const res = await axios.post(
      `${GITHUB_API}/user/repos`,
      { name: repoName, private: false, description: "Portfolio generated by LaunchFolio" },
      { headers }
    );
    return res.data;
  } catch (err) {
    // 422 means the repo already exists — fetch it instead
    if (err.response?.status === 422) {
      console.log(`[GitHub] Repo "${repoName}" already exists, reusing it`);
      const userRes = await axios.get(`${GITHUB_API}/user`, { headers });
      const owner = userRes.data.login;
      const repoRes = await axios.get(`${GITHUB_API}/repos/${owner}/${repoName}`, { headers });
      return repoRes.data;
    }
    throw err;
  }
};

/**
 * Push local generated site to GitHub.
 * Always starts fresh: removes any existing .git, inits with branch "main",
 * commits all files, and force-pushes.
 */
const pushToGitHub = async ({ localPath, repoUrl }) => {
  // 1. Remove any stale .git from previous attempts
  const dotGit = path.join(localPath, ".git");
  if (fs.existsSync(dotGit)) {
    fs.rmSync(dotGit, { recursive: true, force: true });
    console.log("[GitHub] Cleaned stale .git directory");
  }

  // 2. Fresh init with main branch
  const git = simpleGit(localPath);
  const gitUrl = repoUrl.replace("https://", `https://${GITHUB_TOKEN}@`);

  await git.init(["--initial-branch=main"]);
  await git.addConfig("user.email", "bot@launchfolio.app");
  await git.addConfig("user.name", "LaunchFolio Bot");
  await git.add(".");
  await git.commit("Initial portfolio commit generated by LaunchFolio");
  await git.addRemote("origin", gitUrl);
  await git.push("origin", "main", ["--force"]);

  console.log("[GitHub] Pushed to", repoUrl);
};

/**
 * Full GitHub flow — create repo and push code.
 * @param {Object} params
 * @param {string} params.portfolioId
 * @param {string} params.userName
 * @param {string} params.localPath
 * @returns {{ repoUrl: string, fullName: string }}
 */
const publishToGitHub = async ({ portfolioId, userName, localPath }) => {
  const repoName = `launchfolio-${userName.toLowerCase().replace(/\s+/g, "-")}-${portfolioId.slice(-6)}`;

  const repo = await createRepo(repoName);
  await pushToGitHub({ localPath, repoUrl: repo.html_url });

  return { repoUrl: repo.html_url, fullName: repo.full_name };
};

module.exports = { publishToGitHub };
